# Generated by Django 2.0.7 on 2018-07-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufac_date',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
