# Generated by Django 2.0.7 on 2018-08-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180803_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='img_back',
            field=models.ImageField(blank=True, upload_to='store/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_front',
            field=models.ImageField(blank=True, upload_to='store/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_ineer',
            field=models.ImageField(blank=True, upload_to='store/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_side',
            field=models.ImageField(blank=True, upload_to='store/'),
        ),
    ]
