# Generated by Django 2.0.7 on 2018-08-03 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180803_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_ineer',
            new_name='img_inner',
        ),
    ]
