# Generated by Django 2.0.7 on 2018-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_code',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
