# Generated by Django 2.0.7 on 2018-08-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart_for_pad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_for_pad',
            old_name='p_code',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='p_code',
        ),
        migrations.AlterField(
            model_name='cart_for_pad',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
