# Generated by Django 2.0.7 on 2018-08-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20180816_2342'),
        ('store', '0014_auto_20180817_0540'),
    ]

    operations = [
    ]
