# Generated by Django 2.0.7 on 2018-08-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20180813_0650'),
        ('store', '0014_auto_20180816_2342'),
    ]

    operations = [
    ]
