# Generated by Django 2.0.7 on 2018-08-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_merge_20180820_0642'),
        ('store', '0021_auto_20180822_1358'),
    ]

    operations = [
    ]
