# Generated by Django 2.0.7 on 2018-08-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20180823_1931'),
        ('store', '0028_auto_20180824_1347'),
    ]

    operations = [
    ]
