# Generated by Django 2.0.7 on 2018-08-22 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_for_Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_str', models.CharField(max_length=100)),
                ('first_date', models.CharField(max_length=100)),
                ('delivery_period', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('type_str', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=20)),
                ('component', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('price', models.IntegerField()),
                ('price_before', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cart_for_subscription',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Type'),
        ),
        migrations.AddField(
            model_name='cart_for_subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
