# Generated by Django 2.0.7 on 2018-08-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=20)),
                ('component', models.TextField()),
                ('detail', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
