# Generated by Django 2.0.7 on 2018-08-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_for_subscription',
            old_name='subscription_type',
            new_name='type',
        ),
    ]
