# Generated by Django 2.0.7 on 2018-08-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_type_price_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_str',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
