# Generated by Django 2.0.7 on 2018-08-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20180822_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_for_subscription',
            name='first_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
