# Generated by Django 2.0.7 on 2018-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20180822_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_for_subscription',
            name='delivery_period',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
