# Generated by Django 2.0.7 on 2018-08-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20180823_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_for_subscription',
            name='first_date',
        ),
    ]
