# Generated by Django 2.0.7 on 2018-08-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180812_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='birth_day',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='birth_month',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='birth_year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
