# Generated by Django 2.0.7 on 2018-08-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180812_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='user',
        ),
    ]
