# Generated by Django 2.0.7 on 2018-08-22 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notice_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 22, 9, 3, 11, 343633, tzinfo=utc)),
        ),
    ]
