# Generated by Django 2.0.7 on 2018-08-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_list', '0002_auto_20180822_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
