# Generated by Django 2.0.7 on 2018-08-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailconfirm'),
        ('accounts', '0003_auto_20180822_1453'),
    ]

    operations = [
    ]
