# Generated by Django 2.0.7 on 2018-08-12 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_auto_20180804_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='password',
        ),
        migrations.AddField(
            model_name='information',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
