# Generated by Django 2.0.7 on 2018-08-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('detail', models.TextField()),
                ('volume', models.IntegerField()),
                ('size', models.IntegerField()),
                ('manufac_date', models.CharField(max_length=30)),
                ('useby_date', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('ingre', models.TextField()),
                ('order', models.IntegerField()),
            ],
        ),
    ]
