# Generated by Django 2.0.7 on 2018-08-19 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='주문상품')),
                ('amount', models.PositiveIntegerField(verbose_name='총 결제금액')),
                ('buyer_name', models.CharField(max_length=50, verbose_name='주문자 이름')),
                ('buyer_email', models.CharField(max_length=100, verbose_name='주문자 이메일')),
                ('buyer_tel', models.CharField(max_length=11, verbose_name='휴대폰번호')),
                ('recipient_name', models.CharField(max_length=50, verbose_name='수령인 이름')),
                ('recipient_tel', models.CharField(max_length=11, verbose_name='휴대폰번호')),
                ('recipient_postcode', models.CharField(max_length=10, verbose_name='우편번호')),
                ('recipient_add', models.CharField(max_length=100, verbose_name='주소')),
                ('recipient_memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='배송메모(선택)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
