# Generated by Django 2.0.7 on 2018-08-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_recipient_add_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipient_postcode',
            field=models.CharField(max_length=10, verbose_name='우_편번호'),
        ),
    ]
