# Generated by Django 2.0.7 on 2018-08-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180821_0658'),
        ('cart', '0003_auto_20180822_1344'),
    ]

    operations = [
    ]
